version: '3'


services:
    postgres-db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: Password12!
        ports:
            - 8081:5432
    mysql-db:
        image: mysql/mysql-server:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: testytest
        ports:
            - 8082:3306
    oracle:
        image: sath89/oracle-12c
        restart: always
        ports:
            - 8080:8080
            - 1521:1521
    adminer:
        image: adminer
        restart: always
        ports:
            - 8083:8083
