version: '3'


services:
    postgres-db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: Password12!
        ports:
            - 8081:5432
    mysql-db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: testytest
        ports:
            - 8082:3306
#    oracle:
#        image: truevoly/oracle-12c
#        restart: always
#        ports:
#            - 8080:8080
#            - 10521:1521
    informix:
        image: ibmcom/informix-developer-database:14.10.FC5DE
        restart: always
        tty: true
        user: root
        environment:
            LICENSE: accept
            ONCONFIG_FILE: onconfig
            RUN_FILE_PRE_INIT: my_post.sh
        ports:
            - 9088:9088
            - 9089:9089
            - 27017:27017
            - 27018:27018
            - 27883:27883
        privileged: true
        volumes:
             - ./informix-server:/opt/ibm/config
    adminer:
        image: adminer
        restart: always
        ports:
            - 8083:8083
